modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/emmanueltremblay9-stack/Immersive-Farming-Mod-Porting/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
credits="Original Immersive Farming by Etyl. Original assets credited to Peter. AstikorCarts credit preserved where compatibility/history is relevant."
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="immersiveengineering"
    type="optional"
    versionRange="[1.21.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="astikorcarts"
    type="optional"
    versionRange="[1.21.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="astikorcartsredux"
    type="optional"
    versionRange="[1.21.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="astikorredux"
    type="optional"
    versionRange="[1.21.1,)"
    ordering="AFTER"
    side="BOTH"
